'use strict'
const fs = require('mz/fs')
const co = require('co')

module.exports = co.wrap(function * (content) {
  const file = './CHANGELOG.md'

  let exists
  try {
    yield fs.access(file)
    exists = true
  } catch (err) {
    exists = false
  }

  if (exists) {
    const oldContent = yield fs.readFile(file, 'utf8')
    const credit = `---

Generated by [changelog.md](https://github.com/egoist/changelog.md)`
    yield fs.writeFile(file, content + oldContent + credit, 'utf8')
    return true
  }

  yield fs.writeFile(file, content, 'utf8')
  return false
})
